#pragma once

#include <vulkan/vulkan.h>

#define TQ_RENDERER_MAX_GPUS 4
#define TQ_RENDERER_MAX_DEVICE_QUEUE_FAMILIES 4
#define TQ_RENDERER_MAX_QUEUE_FAMILY_PROPERTIES (TQ_RENDERER_MAX_DEVICE_QUEUE_FAMILIES * sizeof(VkQueueFamilyProperties))
#define TQ_RENDERER_MAX_SWAPCHAIN_IMAGES 3